image: Visual Studio 2017

before_build:
- nuget restore hw_task1.2/hw_task1.2.sln

build:
project: hw_task1.2/hw_task1.2.sln

test_script:
- nunit3-console  hw_task1.2/hw_task1.2.sln \
--result=myresults.xml;format=AppVeyor